### ISSUE TITLE
Making presentational components functional

### ISSUE THREAD

**Issue by goku321** [clintonwoo/hackernews-react-graphql#27]
I would suggest to make presentational components functional instead of class based. Functional components are not “dressed up” with any of the capabilities of React component objects and hence there may be performance advantages.

**Comment by clintonwoo** [comment]
I've done a massive update to this project and converted almost all the components to functional. They are a lot cleaner now since the hooks are less verbose than classes. The Apollo hooks are easier to reason about than the `graphql` HoC too.

Wasn't able to use hooks for `next` router since in `withData` it passes the router when doing SSR. Maybe I'll be able to think of a solution for this later.
