### ISSUE TITLE
Use a real database

### ISSUE THREAD

**Issue by benmccann** [clintonwoo/hackernews-react-graphql#39]
Thanks so much for providing this. It's very interesting to see these technologies used together

One thing I noticed is that it looks like there is no database and perhaps data is just stored in memory. I was wondering what your thoughts were on adding a database like Postgres and using a data access layer like Prisma? It would also be interesting to see an example of that. Potentially I could add it if it's something you're open to, but no promises since I'm not sure yet whether I would have the time

**Comment by clintonwoo** [comment]
Yeah it's cool but that would be like a separate project really. You are welcome to fork if you want to provide it!

It's using in-memory data because YCombinator provides a public Hacker News API. They have limited data available though so this app mostly just implements those things that are available.
